### ISSUE TITLE
'DR_SF12' was not declared in this scope

### ISSUE THREAD

**Issue by tobiascrackz** [matthijskooijman/arduino-lmic#283]
using arduino IDE
after updating lmic library to 3.2.0 i get in previously working code (ttn-abp.io) following compile error:

'DR_SF12' was not declared in this scope

**Comment by matthijskooijman** [comment]
Version 3.2.0 sounds like the https://github.com/mcci-catena/arduino-lmic flavor of LMIC (at least not this one), so I suggest you verify which flavor you have and seek support there.
